# Generated by Django 4.2.3 on 2023-07-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_horastotales'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='horastotales',
            field=models.IntegerField(default=0),
        ),
    ]
